# Make this Makefile better later

build: ./src/main.c ./src/io.c ./src/algorithms.c ./inc/io.h ./inc/algorithms.h
	gcc -o ./bin/main ./src/main.c ./src/io.c ./src/algorithms.c -I./inc/ -Wall -Wextra -lm

